server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # SPA — todas as rotas caem no index.html
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Proxy da API para o container da API REST
  location /api/ {
    proxy_pass http://api:3333/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
