sonar.projectKey=victor-moy_gestao-patrimonio
sonar.organization=victor-moy
sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests,frontend/src/tests
sonar.exclusions=frontend/src/tests/**
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
